sudo: required
services:
  - docker

before_install:
  - docker build -t iboretska/docker-learn-on-react -f Dockerfile.dev .

script:
  - docker run -e CI=true iboretska/docker-learn-on-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-north-1"
  app: "Docker learn on react"
  env: "Dockerlearnonreact-env"
  bucket_name: "elasticbeanstalk-eu-north-1-260580745609"
  bucket_path: "docker-learn-on-react"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY"
